### ISSUE TITLE
Add support for Show More/Show Less to Today widget

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#1211]
Many Today screen widgets allow the user to show more or less content. We should support the same. 'Show More' should show up to 4(?) bookmarks. 'Show Less' should show 1.

**Comment by chadsy** [comment]
As an increment on this inhancement, I'd love to see:

1. The cells in the widget be "concentrated" to just maybe 2 lines: e.g. feature their name (which the user can shorten/mnemonize), status, and next N times (3 seems reasonable)
1. The Show More / Less to switch between max(2, N) and max(10, N)
1. There be some indication of "freshness" of the fetch, which is sometimes crucial for widgets because they can be slow to update
