### ISSUE TITLE
After building project no region list

### ISSUE THREAD

**Issue by a1ex4nd3r** [OneBusAway/onebusaway-iphone#1247]
Hi,

after building the project from dev branch without errors, no regions are shown in settings. 
Tried the master branch and I'm getting following error:

`<unknown>:0: error: module compiled with Swift 4.0 cannot be imported in Swift 4.0.3: /Repositories/New/onebusaway-iphone-master/OBAKit/../Carthage/Build/iOS/PromiseKit.framework/Modules/PromiseKit.swiftmodule/x86_64.swiftmodule`

If there is a latest stable commit that I can run with which one is it?

### Steps to reproduce the behavior
Dev branch version:
1. build project with latest commits
2. start app in simulator
3. check region list

### Screenshot of the issue (if applicable)
Dev branch version:
[http://prntscr.com/hv5ymc](http://prntscr.com/hv5ymc)

### App Version/Hardware
System: MacOS High Sierra
xCode: 9.2
Swift 4

Any help appreciated.
Regards

**Comment by aaronbrethorst** [comment]
There’s a race condition that is being exacerbated by recent changes. I’m investigating but haven’t found the cause yet. 

Regarding the build issue on master: that’s because those Carthage frameworks were compiled with an older version of the swift compiler than what you’re using. I need to add a note to the README about that.

**Comment by aaronbrethorst** [comment]
I have added a note to the README about the Carthage issue: https://github.com/OneBusAway/onebusaway-iphone/commit/39c22df90c0d52287529a409f5ed11d3e045b34f
