### ISSUE TITLE
on "agencies" list, indicate which agencies have real-time data and which are schedule only

### ISSUE THREAD

**Issue by alanborning** [OneBusAway/onebusaway-iphone#1443]
That's it!

**Comment by aaronbrethorst** [comment]
@alanborning What's the property I can reference for this information?

**Comment by barbeau** [comment]
@aaronbrethorst To my knowledge we don't have anything in the Regions API that could be used for this, so there isn't a good way to support this currently. I'm a little hesitant to bake this into the Regions API too, because the agency can turn real-time on or off at any given time without telling us.

@alanborning What's the use case for this feature?

**Comment by alanborning** [comment]
The use case is people wondering why their bus times are always schedule only.  But given the concern about baking this into the Regions API, let's just drop this idea.

**Comment by barbeau** [comment]
@alanborning Ok, thanks!
