### ISSUE TITLE
search not working when far from current location

### ISSUE THREAD

**Issue by alanborning** [OneBusAway/onebusaway-iphone#1456]
Search is working OK for Puget Sound.  However, when I try to do a search for a route or stop in other regions the map says "No stops at this location", even though there are.  I tried San Diego, Tampa, and Spokane, with the same result.

The two screenshots show this for Tampa.  The first image shows the map for a randomly chosen stop (Marion St @ Zack St).  Routes 8 and 20 stop there.  Then, keeping the map at the same location, I search for route 8, and get the second image, which says "No stops at this location" even though clearly there are.

The same thing happens for searching for a stop number.  App 19.1.0, running on an iPhone 7, iOS version 13.1.3

![IMG_3006](https://user-images.githubusercontent.com/918773/68451862-5a091e00-01a5-11ea-9032-e69503df03e5.PNG)

![IMG_3007](https://user-images.githubusercontent.com/918773/68451876-67260d00-01a5-11ea-8993-400be469c267.PNG)

**Comment by barbeau** [comment]
This sounds similar to an issue we had on Android. IIRC, search uses the stops-for-location and routes-for-location API endpoints, which requires a radius for search from a location. If your real-time location is always used, then search for other regions never returns results because the results are all outside the typical radius being used. IIRC we fixed this on Android by using the map view center as the search point if the real-time location was a large distance away from the map view center.

**Comment by alanborning** [comment]
That sounds a good diagnosis! I changed the title to be clearer about the issue.
