### ISSUE TITLE
Change GitHub project name to onebusaway-ios

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#180]
In preparation for iPad support.

**Comment by barbeau** [comment]
We have [iPad support now](https://github.com/OneBusAway/onebusaway-iphone/pull/916).

@aaronbrethorst is renaming the repo worth the potential hassle?  I tend to avoid these things due to potential friction, although Github promises it will forward everything - https://help.github.com/articles/renaming-a-repository/.

**Comment by aaronbrethorst** [comment]
> I tend to avoid these things due to potential friction, although Github promises it will forward everything

Concur. Thanks, all :)
