### ISSUE TITLE
show departure time rather than arrival time

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#221]
From what I can tell the times being shown are vehicle arrival times but I think we should be showing the departure times instead. Some vehicles have layovers so the departure time is more useful.

**Comment by aaronbrethorst** [comment]
what's the proper field in the API for this?

**Comment by barbeau** [comment]
From arrivals-and-departures-for-stop:
http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/arrivals-and-departures-for-stop.html

>* scheduledArrivalTime - scheduled arrival time, ms since unix epoch
* scheduledDepartureTime - scheduled departure time, ms since unix epoch

>...

>* predictedArrivalTime - predicted arrival time, ms since unix epoch, zero if no real-time available
* predictedDepartureTime - predicted departure time, ms since unix epoch, zero if no real-time available

FWIW, OBA Android shows departure information for the first stop in the trip, and arrival information for all other stops:

        // If this is the first stop in the sequence, show the departure time.
        if (info.getStopSequence() != 0) {
            scheduled = info.getScheduledArrivalTime();
            predicted = info.getPredictedArrivalTime();
        } else {
            scheduled = info.getScheduledDepartureTime();
            predicted = info.getPredictedDepartureTime();
        }

This does result in showing arrivals times for trips terminating at a transit center, which may not be intuitive to riders new to transit.  More on this discussion, and a possible way to allow filtering for this in the app, is at https://github.com/OneBusAway/onebusaway-application-modules/issues/148.

**Comment by aaronbrethorst** [comment]
cool, thanks sean!

**Comment by aaronbrethorst** [comment]
this is now done.
