### ISSUE TITLE
Info label is off-center for some stops

### ISSUE THREAD

**Issue by caitbonnar** [OneBusAway/onebusaway-iphone#327]
Just noticed that the info button is off-center for some stops in the production version of OBA:
![img_6435](https://cloud.githubusercontent.com/assets/4627278/4520988/5c882c7c-4d03-11e4-85d2-fbaf15de8b3b.PNG)

Will look into fixing soon after I handle a couple other things, unless someone else wants to pick this up.

**Comment by aaronbrethorst** [comment]
Looks to be 'magically' fixed in later versions of iOS. I expect it was a bug in the OS. Since it doesn't impair operation on older versions, I'm inclined to close as 'won't fix.'

![simulator screen shot dec 6 2015 1 32 27 am](https://cloud.githubusercontent.com/assets/2254/11612696/5f383790-9bb9-11e5-8d28-7abbac0744ae.png)
