### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by Wizecoder** [OneBusAway/onebusaway-iphone#338]
I'm working on some ideas for an iOS redesign, and was hoping to get some feedback. 

I wanted to focus on a map centric design (e.g. have the map on screen in some capacity as much as possible so positional context of stops isn't lost), and wanted to try and get rid of the tab bar, so the mockups are based around slide-outs for the list of stops, settings, and stop details. I'm still not sure about the stop list, I'm thinking of using a segmented control instead of the different table sections, because although mostly similar, the lists might have a couple of differences (namely the bookmarked stops with groups). But I don't know if either is a good option (segmented controls are always a bit iffy), so I still need to consider some things.

Any thoughts?

(note: this is just a stock map image, the actual map display I'm thinking will stay about the same as it is now)

cc @barbeau @jrharshath

[Link to the Sketch file if anyone wants it](https://www.dropbox.com/s/5d4uw9j9zp8o3rn/design_mockup.sketch?dl=0)

![start here](https://cloud.githubusercontent.com/assets/354123/4855429/00a4ea34-60a5-11e4-9ffa-101418d40c8c.png)
![stop details](https://cloud.githubusercontent.com/assets/354123/4855430/0705ad5a-60a5-11e4-9eca-608bf85a5653.png)
![stops](https://cloud.githubusercontent.com/assets/354123/4855432/08a47ca4-60a5-11e4-82b0-313024efc65d.png)
![settings](https://cloud.githubusercontent.com/assets/354123/4855433/0ab9f988-60a5-11e4-9e22-80ccf68b76de.png)

**Comment by aaronbrethorst** [comment]
I believe @dragonc may have some thoughts about this. I'd love to have her chime in.

**Comment by jrharshath** [comment]
Hey guys,

I had mentioned earlier that I'm doing a study with transit riders. I recently finished doing my surveys, and a couple of results are quite relevant to this discussion of bookmarks.

* 84% of all riders use a maximum of four routes regularly, with 75% of these using only 3 routes regularly
* 75% of all riders repeatedly use just two stops on any given route.

Given this level of repeat behaviour, I think bookmarks/favourites/recents definitely take precedence over a map/search based based stop finding mechanism. Besides, I personally feel finding a stop on a map would be harder than to find on a list of nearby stops (something I need to verify by experiment).

As part of the survey, I explored the attitude towards schedules and/vs realtime information. I repeatedly found that schedules were valued because they allowed planning into the future, and also contained the expected times of arrival. This means OBA should not only show realtime arrivals, but also allow the users to easily view the schedules of their most frequently used routes as well (OBA has this information from the GTFS files).

I'm currently drawing up some wireframes of a design that incorporates this feedback and building a video showing how this interaction can work. I'll share it with you all sometime next week. Feedback will be greatly appreciated :)

**Comment by revoltpuppy** [comment]
If you want to get rid of the UI, I explore you to do lots of actual live testing! Often designers like to remove useful UI because it is "ugly". Please do not fall for this trend. Remove everything that's unnecessary, but nothing more.

Personally, the UI does not get in the way and lets me easily and intuitively switch between Map and Bookmarks. Obfuscating either of these for the sake of "prettiness and simplicity" would be a huge annoyance.

**Comment by aaronbrethorst** [comment]
@revoltpuppy I appreciate the sentiment, and promise that we won't get rid of useful UI because it's "ugly." :) I just emailed you to see if you'd be interested in beta testing future updates to OBA. I'd love to make sure that I get your opinion on UI redesigns to ensure that I don't do just that.

@jrharshath I'd love to see those wireframes.

Everyone else - I'm closing this task as it seems to not have an immediate goal. Please feel free to open up new tasks as needed.
