### ISSUE TITLE
Escape characters like '&' and '/' in searches

### ISSUE THREAD

**Issue by weekilter** [OneBusAway/onebusaway-iphone#345]
Unless I'm not understanding how the application works there's a major problem with search.  If you go to the maps tab and input any address it brings the result "no routes found" even for locations where there should be multiple results e.g. for Seattle putting in the location 3rd Ave & Pike St it shows no routes found.

**Comment by bbodenmiller** [comment]
Looks like some address searches work while others do not. For example "915 Northwest 45th Street, Seattle, WA 98107" works but "915 Northwest 45th Street" does not. The later however works fine in Google Maps, Apple Maps, & The Transit App.

**Comment by barbeau** [comment]
Are the working addresses close to your real-time location when you perform
the search?

I know the stop and route searches have radius limiters based on your
real-time location, but I'm not sure if address search on iOS has this same
radius limiter.  If close addresses work but far away ones don't then this
likely the issue.

**Comment by bbodenmiller** [comment]
For me it's a mater of how the address is formatted rather than where I am when I do the lookup. It's like the address to geo location lookup isn't working. I believe the radius issue only applies to route searches rather than trying to get the map to zoom on a specific address.

**Comment by barbeau** [comment]
Yeah, sounds like its an issue with the geocoder then.

@caitbonnar IIRC OBA iOS is using the Google Geocoder web API?

**Comment by aaronbrethorst** [comment]
Our options are either to consider this a backend bug, or to look into using Apple's reverse geocoding service and feed the lat and long points it gives us to the OBA backend (assuming it can accept lat and long). In an ideal world, I'd prefer depending on the OBA backend for all of this, but I'd  prefer doing the latter for the sake of expediency. Does anyone know if the OBA backend will accept lat and long?

**Comment by barbeau** [comment]
@aaronbrethorst IIRC OBA iOS is using the Google Geocoder web API for address->lat/long conversion.  Also, IIRC OBA back-end deployed in Seattle/Tampa that works with apps doesnt have a geocoder API endpoint.

**Comment by bbodenmiller** [comment]
Works for me if I use "and" rather than "&". Any ideas what the issue is with the "&"?

**Comment by caitbonnar** [comment]
@bbodenmiller Yeah, see my above comments. My guess is that it's the same
encoding issue we had with the custom API url. I'll double check tomorrow
to make sure. Probably best to create a helper function that handles this
from now on.

**Comment by caitbonnar** [comment]
Looked into this issue yesterday. As I suspected, it is an encoding problem. But it is a bit trickier to handle than other cases. This is because we have a method called [escapeStringForUrl:url](https://github.com/OneBusAway/onebusaway-iphone/blob/5b9c55fd18b3da223d1cd85f68679fd7340c4f7f/Libraries/aaronbrethorst-onebusaway-iphone-common-fa9a21b/Classes/Control/Common/OBAModelService.m#L417) that replaces special characters in an ```NSString``` manually. This used to work fine, but when Google geocoding changed to their newest version, we suddenly had an encoding problem [that I fixed myself](https://github.com/OneBusAway/onebusaway-iphone/commit/35330dd86ee8ad68ba132edbe78638c9010f366b) by using a built-in method for converting to UTF-8. Only using ```escapeStringForUrl``` on the address doesn't seem to work for some reason. 

However, the built-in method doesn't account for the '&' and '/' characters, which makes sense, as they are allowed characters in a URL. So when a user types in an address using the '&' character, which should definitely be allowed in this case, it doesn't encode correctly. I think right now we are actually double encoding the address, which is even worse.

@aaronbrethorst Thoughts on how to fix this? I've been thinking of adding a new category to ```NSString```, [as is recommended here](https://github.com/OneBusAway/onebusaway-iphone/commit/35330dd86ee8ad68ba132edbe78638c9010f366b), since even though it's an old post, it still seems to be relevant. But not sure if this is the best way to go, or if it would necessarily solve the problem.

**Comment by aaronbrethorst** [comment]
Looks like Google has improved their geocoding service, as "915 Northwest 45th Street" now seems to work perfectly. It sounds like the one remaining issue here is the handling of special characters as mentioned by @caitbonnar above.
