### ISSUE TITLE
Remove redudant "About this stop" link

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#386]
I believe we should remove the bottom redundant "About this stop" link similar to what was done with the bookmarks link in https://github.com/OneBusAway/onebusaway-iphone/pull/385. Doing so would also fix https://github.com/OneBusAway/onebusaway-iphone/issues/384.

**Comment by aaronbrethorst** [comment]
:+1: concur

**Comment by caitbonnar** [comment]
Actually, could you hold out on taking this out for a bit? The reason the additional About this Stop link is for accessibility purposes -- deaf/blind and low-vision folks as well as people with motor impairments that I've talked to have trouble with the info button since it is a small, low contrast tappable target, but are better with the About This Stop button. However, it has also been reported that keeping the button next to the stop name is good for our VoiceOver users and many general users who don't scroll down below the arrival time table. 

I think what would be a suitable alternative (rather than having duplicate methods for getting to StopInfo) would be to improve the info button to either a custom icon or a more visible/tappable info button. If anyone can think of a better way of incorporating StopInfo in a way that is intuitive and meets the needs of users with varying abilities (since that is the whole goal of the project anyway), then please feel free to suggest one. As of right now, I'm really hesitant about taking out the extra table cell, even if it is only there to benefit a "few" users.

**Comment by caitbonnar** [comment]
Also, I think it is fine to remove the table cell when the region doesn't have StopInfo available as mentioned in #384.

**Comment by aaronbrethorst** [comment]
Stopinfo is now dead. Mooted.
