### ISSUE TITLE
Map arrows point in wrong direction after rotating the map

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#390]
See picture.
![oops](https://cloud.githubusercontent.com/assets/2254/6741860/540f4fa0-ce48-11e4-9b23-075e85a5a9b4.jpg)

**Comment by yogipatel** [comment]
Yikes. A couple of options:

1. Remove the direction arrows altogether. Are they really necessary since the side of street usually implies direction? Google Maps, for example, doesn't use these.
2. Disallow map rotation.
3. Rotate the icon with the map. One approach would be to separate the arrow from the icon, create an icon object, and provide it a heading to draw to (relative to the actual stop direction). This isn't as straight-foward as it might seem as MKMapView doesn't provide callbacks as the map is rotating — it fires only once the rotation/scaling is complete. This could be remedied by a gesture recognizer that provides on-the-fly callbacks, but that might not be very performant.

My vote would be to drop the arrows completely, as I've never found them really useful…but I'm new around here :smile:.

**Comment by bbodenmiller** [comment]
I think disabling rotation may be the best option. I think too many people are accustomed to the arrows to remove them.

**Comment by aaronbrethorst** [comment]
I'll :+1: that. I find the arrows useful as it allows me to figure out which stop I want without having to zoom in too far. So, disallow map rotation.
