### ISSUE TITLE
Meters showing under minutes

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-iphone#458]
Never seen this before... Is this what is supposed to show if the API returns distance bus is from stop but not time?

![image](https://cloud.githubusercontent.com/assets/1192780/11150104/058b2c60-89db-11e5-83f6-105c9353e787.png)

**Comment by barbeau** [comment]
@bbodenmiller Are you using Puget Sound region (vs. a custom API URL)?

**Comment by bbodenmiller** [comment]
Yep on Puget Sound.

**Comment by tomtclai** [comment]
I found the responsible code here:
https://github.com/OneBusAway/onebusaway-iphone/blob/f41cac0d55d1a48f0e006c72326d89b4702645a8/controls/table_cells/OBAArrivalEntryTableViewCellFactory.m#L50

**Comment by barbeau** [comment]
Yeah, looks like iOS shows distance if there is real-time info but no
predicted departure time.  All arrivals-and-departures-for-stop API
responses include distance to stop info in the status element, even when
real-time info isn't available (in that case it's interpolated).  I believe
it's typically a fairly rare occurrence where real-time is available but no
departure time exists, which is why this doesn't surface more often.  There
might have been a server side code change or source data change that caused
this to surface too.  For example, I think you would see this if the source
GTFS-rt TripUpdates feed stopped but the VehiclePositions feed continued.

**Comment by aaronbrethorst** [comment]
I saw this yesterday too, but I haven't been able to repro it yet today. If we can come up with data that reproduces it, I'll happily get a fix together asap, but otherwise, let's keep this as a placeholder for a bug fix for a future release.

**Comment by bbodenmiller** [comment]
Looks like others are seeing this as well: https://m.facebook.com/groups/367248491525?view=permalink&id=10153223813876526
