### ISSUE TITLE
Reduce frequency of region updates to once per week

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#678]
Per @barbeau 

> IIRC OBA iOS hits the Regions API on every startup. This really isn't necessary, and we could get away with far less frequent updates, which should help with both device and server performance. OBA Android refreshes weekly. If you're overhauling the region-related code you might want to consider this change. This also helps us roll out features like trip planning (adding an OTP URL to a region) in a little more gradual manner, rather than flipping the switch and immediately going live in production for all users. It's a crude method for controlling a rollout server-side, but it seems to work ok.

I was imagining this would work as follows:
- at launch, the app would check to see if a 'next region update date' had been set in user defaults.
- If it has been set, check to see if the update date is in the past and update regions if true, setting the next update date to be 1 week in the future.
- If it has not, download regions immediately and then set the next region update date to be a random value in the range of 0 to 7 days. After that, the next updates can always occur at 1 week intervals.
- If the app version has changed since the last launch (e.g. 2.6.0 -> 2.6.1), then update regions.
- If the cached version of regions.json is missing, then grab the bundled version and kick off an update.

(**note: the bullet points above are now somewhat incongruent, and need to be updated**)

The goal here is to avoid a [thundering herd problem](https://en.wikipedia.org/wiki/Thundering_herd_problem) that might develop from everyone's updated OBA apps ending up with approximately the same region update date. By randomly spreading these values out over the course of a week we should be able to at least ameliorate the problem (although obviously Monday mornings are likely to have higher traffic, since they'll absorb most of the people whose updates land on Friday night - Sunday night).

**Comment by bbodenmiller** [comment]
Has anyone considered serving the Regions API via GitHub either as the primary source or atleast a backup?

**Comment by aaronbrethorst** [comment]
I'd rather not treat them as a means to serve files to end users. It might work fine today, but if/when they change their minds about being a file host, then any users on older versions of apps that point to GitHub are going to be in trouble.

**Comment by barbeau** [comment]
@aaronbrethorst On OBA Android, we have similar process to what you outline above, with the minor difference that we store the timestamp of the last successful update.  On each startup, we check to see if it's been over 1 week since the last successful update.

@bbodenmiller I have an instance of the Regions API hosted on AWS - http://onebusaway-regions.s3-website-us-east-1.amazonaws.com/regions-v3.json, courtesy of Cambridge Systematics.    I've had this on standby since when the previous failures occurred as a backup.  Everything has been running smoothly since then, though, so I haven't had a good reason to disrupt the status quo.

**Comment by barbeau** [comment]
@aaronbrethorst Sorry, I actually misread your post - on Android we currently *aren't* using a randomized value to set the next update time, although that's a good idea and something we should consider.

On a related note - something else we added relatively recently to OBA Android is to force a Regions API update on an app update.  This was necessary to pick up Regions API data that was required for new features such as issue reporting (Open311 URL) and trip planning (OTP server URL).  So I'd suggest implementing or at least planning for that now.  This would likely be the biggest cause behind reducing randomness in Region API updates on Android.

**Comment by bbodenmiller** [comment]
Something else you'll probably want is the ability for a user to force an update.

Rather than forcing an update on app update what about only doing the update if the app looks for something and does not find it in the local copy?

**Comment by barbeau** [comment]
We do support allowing user to force a refresh via a refresh button on the
regions list screen on Android.  That's useful for troubleshooting and
testing.

Doing per-element refresh doesn't really work, because looking at local
data you wouldn't know if the element was supposed to be missing or not.
The only reliable way is to refresh your local state from the Regions API.
