### ISSUE TITLE
Reload bookmarked stops based on proximity 

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#704]
Instead of reloading every bookmark every 30 seconds, reload them every 15s - 2 minutes based on the user's proximity to the stop. That way, they can get the info they care about sooner without consuming unnecessary bandwidth.

**Comment by barbeau** [comment]
Let me know what distance/interval pairs you use for this and we can match
on Android.

**Comment by aaronbrethorst** [comment]
I'm thinking about trying something really simplistic to start with, like:

#1 is 15s
2-3: 30s
4-10: 1m
11+: 2m

And seeing how well/poorly it works :)

**Comment by barbeau** [comment]
We had this feature in another app I worked on a while back, although it
was a prototype and never widely deployed - I'll see if I can dig up what
we used there.

The potential issues are accuracy/precision of (a) device real-time
location, (b) bus stop location, and (c) arrival times.  I've seen (a) vary
widely across devices on Android.  We have an accuracy uncertainty measure
to use (e.g., to throw out positions that have a large accuracy value), but
the accuracy of accuracy uncertainty is sometimes questionable. (b) depends
on the transit agency - I seen some agencies have pristine GTFS datasets,
others are horrible.  For (c), from reports on Android arrival time
predictions seems to be more volatile than over the last few months.
Increasing refresh interval when far away is likely ok, assuming (a) and
(b) above are accurate/precise - if not, this could create problems.
Decreasing interval when close to stop would probably help with the
volatile arrival problem (e.g., to remove outlier predictions more quickly
from user view).

Because of the above, you may want to consider having this be an opt-in
feature until you get a handle on how it performs in the wild, or at least
allow users to turn it off in Settings.
