### ISSUE TITLE
Bookmark Groups should be validated as having non-zero length titles before being created

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#717]
### Expected behavior

A bookmark group without a name cannot be created.

### Actual behavior

It can be created, which causes other problems later on.

### Steps to reproduce the behavior

Create a bookmark group, leave the name blank.

### App Version/Hardware

2.6.0

**Comment by chadsy** [comment]
Thanks @aaronbrethorst for pointing out the additional case of Add Bookmark. After more analysis & discussion, here's where I think this stands:

* The UX of disabling Save is reasonable to indicate that there must be a non-empty group name
* The group model can have a class method to test the viability of creating a new object with the given attributes (in this case, a name that is non-empty)
* I'm going to try to unify the "new group" feature between the two flows; right now, one is an alert view and the other is a new table view (with one item). Because the table view is somewhat odd with just one item, I'm thinking of using the alert popup for both.
* There's another bug in the Add Bookmark flow. If you Group -> Add then Cancel, the bookmark is shown going to the New Group group, but then is never added at all. Opened #734 for this one.

**Comment by aaronbrethorst** [comment]
That all sounds great. I am ready to see that table view removed :)

**Comment by chadsy** [comment]
PR Updated. It unifies both cases on the main Groups view controller, which now has an Edit mode and a Select mode.
