### ISSUE TITLE
Collapse identical routes into one "card"

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/onebusaway-iphone#937]
Personally, I think Android looks better than iOS's. Specifically how Android collapses the same route into one card displaying the next couple of departures versus how iOS dumps all the data into a table. It's better than skimming through a table of unsorted routes just to find the next departure.

<img src="https://cloud.githubusercontent.com/assets/22162410/21954008/9e3c69fe-d9fa-11e6-94ca-35088c805749.png" height=480>
<img src="https://cloud.githubusercontent.com/assets/22162410/21954021/27b7f248-d9fb-11e6-994b-fc359583c19a.jpg" height=480>
We don't have to follow Material Design, like Android, but take a similar approach. Idk, but these are my 2 cents to make iOS more intuitive and on-par with the droids.

@dotTechnoPath @ualch9

**Comment by aaronbrethorst** [comment]
Thanks for the thoughts. Please don't tackle this yet.

**Comment by barbeau** [comment]
Based on user feedback I have mixed feelings about this design myself.
Some thoughts below:

* Some users definitely prefer one to the other - on Android you can toggle
back and forth between sorted by ETA and sorted/grouped by route by tapping
on sort button at top of screen. This definitely isn't obvious to some
users. Default is the old ETA-sorted view, although I think there is a bug
on some devices which has defaulted users to route-sorted view - or user
error in switching. Either way I've gotten complaints from some users who
couldn't figure out how to get to the ETA sorted view (despite tutorial
screen that explains this).
* One purpose of the route-sorted view was to show scheduled times to users
separate from estimated times to help explain the difference. In retrospect
I'm not sure how successful that has been.  One item that bugs me is that
we are showing clock times on ETA sorted view that represent the estimated
arrival time based on real-time info, but on the route sorted view we show
clock times that are scheduled times. Part of me wants to change route
sorted clock times to be real-time as well, but so far I've shied away from
this major change given that users seem to have settled into it.

So I'd definitely recommend introducing this route grouped view as an
option but not the default. And you might want to think closely about the
clock times shown on this view in terms of keeping them consistent with the
original view.

On Jan 14, 2017 11:43 AM, "Aaron Brethorst" <notifications@github.com>
wrote:

Thanks for the thoughts. Please don't tackle this yet.

Sent from my iPhone


> On Jan 14, 2017, at 1:52 AM, Alan Chu <notifications@github.com> wrote:
>
> Personally, I think Android looks better than iOS's. Specifically how
Android collapses the same route into one card displaying the next couple
of departures versus how iOS dumps all the data into a table. It's better
than skimming through a table of unsorted routes just to find the next
departure.
>
>
>
>
>
> We don't have to follow Material Design, like Android, but take a similar
approach. Idk, but these are my 2 cents to make iOS more intuitive and
on-par with the droids.
> @dotTechnoPath @ualch9
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OneBusAway/onebusaway-iphone/issues/937#issuecomment-272635818>,
or mute the thread

**Comment by barbeau** [comment]
Oh,  and that screenshot is older - here's the most recent view with a few
tweaks:

**Comment by aaronbrethorst** [comment]
> So I'd definitely recommend introducing this route grouped view as an option but not the default. And you might want to think closely about the clock times shown on this view in terms of keeping them consistent with the original view.

Notably, iOS _does_ have this feature. I introduced it early(?) last year. It's hidden under filtering and sorting. I think there are two immediate improvements that can be made:

1. Better discoverability of the route sorting/filtering view controller.
2. Improved UI for grouped departures.

In both cases, we will need to start with a design before moving on to implementation.

**Comment by aaronbrethorst** [comment]
I think we're good here. Please reopen on OBAKit if you disagree.
