### ISSUE TITLE
Allow sorting of bookmarks by proximity

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#942]
A user:

> I wish I could sort my bookmarks based on proximity to my current location

## Tasks

- [x] needs design
- [x] needs implementation

**Comment by dotTechnopath** [comment]
I designed an interface that would allow sorting (not just by proximity) on the bookmarks section
here is the mockup: 
![group 2](https://cloud.githubusercontent.com/assets/9895341/22401761/cc5ecc50-e594-11e6-9694-c780b2c1472c.png)

basically I replaced the groups button with the sort button, and now the groups button will only appear when in edit mode. 
what do you think?

**Comment by aaronbrethorst** [comment]
@dotTechnopath thank you for thinking through this. I like the minimal UI surface area, but I don't think we'll be able to use these. A couple things here, and then a few more notes on #955:

- I'd love to get rid of the Recent tab, but it has been growing in importance over the past few releases, and gains another feature in the next one. It now includes records for shared trips, push notification alarms, and recently viewed stops. This design would need to accommodate all of those features.
- I am a bit confused by the nested editing system for groups. I'm not sure what the right solution is, though.
- Needs design for proximity. Including what happens when a bookmark doesn't include any lat, long data to determine proximity.

-----

Here's what I'm imagining for this:

There's a segmented control at the top of the table with two options: `[group] [distance]`

By default, group is selected. When the user taps distance, the controller re-sorts the bookmarks into two sections. The first section is title-less and contains all bookmarks with lat, long values sorted by distance from near to far. The second section is entitled "Unknown Location" (or something), and contains everything else.

**Comment by dotTechnopath** [comment]
Sorry, when I designed the mockup I wasn't trying to get rid of recent tab. sorry for the misunderstanding. It was just a random filler 3rd option for sorting the bookmarks. It could of just of well been "Alphabetical", or "latest added". This way if we wanted to have more then 2 ways of sorting the bookmarks we can just add on to the pop-up menu without making the interface too clunky. 

concerning the nested group thing, my thinking was that because the groups button is basically an "edit" button for groups, I thought it would make more sense that it would live under the edit button.

fair point on the proximity, I think your solution of having 2 sections makes sense and would work.
