### ISSUE TITLE
Arrival and Departure: Animate the vehicle annotation's position

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#975]
### Expected behavior

The vehicle's position should be animated as new data comes in

### Actual behavior

There's no animation

### Steps to reproduce the behavior

Open the arrival and departure controller; wait a minute or two.

### Screenshot of the issue (if applicable)

![simulator screen shot feb 7 2017 2 01 53 pm](https://cloud.githubusercontent.com/assets/2254/22713586/004943a0-ed3e-11e6-9842-e089d64d5314.png)

**Comment by barbeau** [comment]
FWIW, due to limitations in some vehicle GPS update rates, on Android we only animate the change in the buses position on the map if it's less than a distance threshold - from `VehicleOverlay`:

>/**
     * If a vehicle moves less than this distance (in meters), it will be animated, otherwise it
     * will just disappear and then re-appear
     */
    private static final double MAX_VEHICLE_ANIMATION_DISTANCE = 400;

After staring at the map for a while and seeing some buses cross lakes, drive straight through buildings, and take other routes that they obviously couldn't in real life due to a large distance between position updates, this is the distance that I chose to limit that behavior while still providing a smooth transition for more frequent updates.

**Comment by aaronbrethorst** [comment]
Awesome, thanks Sean :)
