### ISSUE TITLE
Improve design of WalkableCell

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-iphone#985]
From a user:

> Walking time addition is neat. Looks like the row isn't tall enough. Also the walking time text may contrast and flow better encapsulated within the green strip.

------

- [ ] Needs final design
- [ ] Needs implementation

**Comment by dotTechnopath** [comment]
I think putting the walking time in the green strip might be confusing to users because the green strip is dynamic and moves around. 

This solution also doesn't account for when a bus isn't available or if none of the buses are within walking time. The user still might want to know how long it takes to walk to a stop.

**Comment by aaronbrethorst** [comment]
fixed in #1045
